# Generated by Django 5.1 on 2025-04-08 13:07

import photo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_client_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='watermark',
            field=models.ImageField(blank=True, editable=False, upload_to='', verbose_name='Защищенное фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=photo.models.upload_to, verbose_name='Фото'),
        ),
    ]
