# Generated by Django 5.1 on 2025-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_watermark_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
